version: '3'
services:
  server:
    build: ./
    restart: always
    ports:
      - "5500:5500"
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
